config/routes.rb
Valet::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#index'

  resources :users do
    resources :relationships
    resources :payments      
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :contact, class_name: "User"

  def add_to_balance(amount)
    update(balance: balance + amount.to_i)
  end

  def sub_to_balance(amount)
    add_to_balance(amount.to_i * -1)
  end
  
  def positive?
    balance > 0
  end

  def negative?
    !positive?
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :creditor, class_name: "User"
  belongs_to :debitor, class_name: "User"

  default_scope { order(id: :desc) }
  
  def of_current_month?(beginning_of_month)
    created_at > beginning_of_month
  end
  
  def is_credit?(current_user)
    current_user.id == creditor_id
  end
  
  def is_debt?(current_user)
    !is_credit?(current_user)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact, class_name: "User" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :relationships
  has_many :contacts, :through => :relationships

  has_many :creditors, through: :purchases, source: :contact
  has_many :debtors, through: :debts, source: :user

  has_many :debts, class_name: 'Payment', foreign_key: :debitor_id
  has_many :purchases, class_name: 'Payment', foreign_key: :creditor_id

  has_many :accounts

  def payments
    debts + purchases
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
  
  private

  def flash_notice(message)
    flash[:notice] = message
  end

  def flash_alert(message)
    flash[:alert] = message
  end

  def flash_notice_now(message)
    flash.now[:notice] = message
  end

  def flash_alert_now(message)
    flash.now[:alert] = message
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:accounts) {
    accounts = current_user.accounts.sort_by { |a| a.contact.firstname }
    AccountDecorator.decorate_collection(accounts)
  }
end

app/controllers/payments_controller.rb
class PaymentsController < SignedInController
  expose(:payment, attributes: :payment_params)
  expose(:debts)
  expose(:purchases)
  #expose(:payments) {  }

  expose(:payments_by_date) {
    beginning_of_month = Date.today.beginning_of_month
    ps = current_user.payments
    ps = PaymentDecorator.decorate_collection(ps)
    ps.group_by { |p| p.created_at.to_date }
  }

  def create
    payed_by_me = params[:payed_by_me]
    debitor_id = params[:payment][:debitor]
    creditor_id = current_user.id
    amount = params[:amount]

    unless payed_by_me
      creditor_id, debitor_id = debitor_id, creditor_id
    end

    payment = Payment.new(creditor_id: creditor_id,
                          debitor_id: debitor_id,
                          amount: amount)
    if payment.save
      update_account_balance(creditor_id, debitor_id, amount)
      if payed_by_me
        flash_notice(t('event.success-add-credit', value: amount, user_name: User.find(debitor_id).firstname))
      else
        flash_notice(t('event.success-add-debt', value: amount, user_name: User.find(creditor_id).firstname))
      end
    end

    redirect_to action: :index
  end

  def destroy
    update_account_balance(debitor_id, creditor_id, amount)
    flash_notice t('event.success-delete-payment')
    payment.destroy
    redirect_to action: :index
  end

  private

  def update_account_balance(creditor_id, debitor_id, amount)
    account_creditor = Account.where(user_id: creditor_id, contact_id: debitor_id).first
    account_creditor.add_to_balance(amount) if account_creditor
    account_debitor = Account.where(user_id: debitor_id, contact_id: creditor_id).first
    account_debitor.sub_to_balance(amount) if account_debitor
  end

  def payment_params
    params.require(:payment).permit(:amount, :debitor, :payed_by_me)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < SignedInController
  expose(:user)
  expose(:relationship)
  expose(:grouped_relationships) {
    Relationship.where(user_id: current_user).decorate.group_by(&:relation_type)
  }
  
  #def index    
    #@amounts = @relationships.each do |relationship|
    #  amount_registered_by_user = Payment.where(user_id: current_user.id, contact_id: relationship.contact_id).map(&:amount).sum
    #  amount_registered_by_contact = Payment.where(user_id: relationship.contact_id, contact_id: current_user.id).map(&:amount).sum
    #  amount_registered_by_user + amount_registered_by_contact      
    #end
  #end

  def create
    email = params[:user][:email] if params[:user]

    unless email.nil? or email.blank?    
      user = User.where(email: email).first
      if user
        Relationship.create!(user_id: current_user.id, contact_id: user.id)        
        flash_notice t('event.success-add-user',
                       user_name: user.decorate.fullname_or_email)
      end
    end    
    flash_error t('error.email-address-not-found', user_email: email) unless flash[:notice]
    
    redirect_to action: 'index'
  end

  def destroy
    relationship.destroy
    redirect_to action: :index
  end

  private
  
  def permitted_params
    params.permit(:relationship => [:email])
  end  
end

app/controllers/signed_in_controller.rb
class SignedInController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < SignedInController
  expose(:user, attributes: :user_params)
  
  def update    
    if user.save
      flash_notice t('event.success-edit-user')
    else
      flash_alert t('event.error-edit-user')
    end

    redirect_to action: :show
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @@markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)

  def render_md(text)
    @@markdown.render(text).html_safe
  end

  def script_exists?(script)    
    script = "#{Rails.root}/app/assets/javascripts/#{params[:controller]}.js"
    available_extensions = %w[.coffee .erb .coffee.erb] + [""]
    available_extensions.inject(false) do |truth, extension|
      truth || File.exists?("#{script}#{extension}")
    end
  end

  def stylesheet_exists?(stylesheet)
    stylesheet = "#{Rails.root}/app/assets/stylesheets/#{params[:controller]}.css"
    available_extensions = %w[.sass .scss] + [""]
    available_extensions.inject(false) do |truth, extension|
      truth || File.exists?("#{stylesheet}#{extension}")
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.container
- if !user_signed_in?
  h2 = t'ui.catch-line'
  p.lead = render_md(t'ui.description')
- else
  - accounts.each do |account|
    .row
      .col-md-6.col-md-offset-3
        - account_container = (account.negative?) ? "red-button" : "green-button"      
        button class="#{account_container} account-balance btn-block" type="button"
          = "#{account.contact.fullname_or_email} #{account.balance}"

app/views/layouts/application.html.slim
doctype html
html
  head
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag params[:controller] if stylesheet_exists?(params[:controller])
    = csrf_meta_tags
    = include_gon
body
    #wrap

      /HEADER
      .container
        .header
          ul.nav.nav-pills.pull-right
            - if user_signed_in?
              li        = link_to t('ui.payments'),       user_payments_path(current_user)
              li        = link_to t('ui.profile'),        user_path(current_user)
              li        = link_to t('ui.relationships'),  user_relationships_path(current_user)
              li.active = link_to t('ui.log-out'),        destroy_user_session_path, method: :delete
            - else
              li        = link_to t('ui.sign-up'),        new_user_registration_path
              li.active = link_to t('ui.log-in'),         new_user_session_path
          h3.text-muted = link_to "Pot′in",               root_path

      /FLASH
      .container
        - if flash[:notice]
          .flash-notice = render_md flash[:notice]
        - if flash[:error]
          .flash-error = render_md flash[:error]

      /BODY
      .container
        .jumbotron
          == yield

    /FOOTER
    #footer
      .container
        p.text-muted
          a[href="#"] = t'ui.contact'

    = javascript_include_tag 'application'
    = javascript_include_tag params[:controller] if script_exists?(params[:controller])

app/views/payments/index.html.slim
.container
  - payments_by_date.each do |date, payments|
    .row
      b.col-md-12 = l(date, format: :default)
    - payments.each do |payment|
      .row.payment-status
        .col-md-6.text-right = payment.contact(current_user).fullname_or_email
        .col-md-1.text-right = payment.decorated_amount(current_user)
        .col-md-1.text-right
          /a.icon-edit   [href=edit_user_relationship_path(current_user, relation)]
          a.icon-delete [href=user_payment_path(current_user, payment) data-method="delete"]

= link_to 'New Payment', new_user_payment_path(current_user), class: "green-button"

app/views/payments/new.html.slim
= form_for payment, url: user_payments_path(current_user), html: { class: "form-inline", role: "form" }

  / PAY|OWN
  .form-group.srm
    input.switch-large [type='checkbox'
                        name='payed_by_me'
                        checked data-on='success'
                        data-off='info'
                        data-on-label =t("action.offer")
                        data-off-label=t("action.own")]
  / AMOUNT
  .form-group.srm
    input.form-control [name="amount" type="number"]
        
  / TO
  .form-group.srm
    = collection_select(:payment, :debitor, current_user.contacts, :id, :firstname, {}, { class: 'form-control' })

  button.green-button type="submit" Effectuer

app/views/relationships/index.html.slim
.container
  - grouped_relationships.each do |relation_type, relations|
    .row
      .col-md-12: b = relation_type
    .row
      - relations.each do |relation|
        .col-md-6.text-right = relation.contact.fullname_or_email
        .col-md-6.text-left
          /a.icon-edit   [href=edit_user_relationship_path(current_user, relation)]
          a.icon-delete [href=user_relationship_path(current_user, relation) data-method="delete"]

= link_to 'New Relationship', new_user_relationship_path, class: "green-button"

app/views/relationships/new.html.slim
= simple_form_for :user, url: user_relationships_path(current_user) do |f|
  = f.input :email
  = f.submit t('action.add-contact'), class: "green-button"

app/views/users/show.html.slim
= simple_form_for user, url: user_path(user), html: { method: :put } do |f|
  = f.input :firstname
  = f.input :lastname
  = f.input :email, disabled: true

  = f.submit t('action.update'), class: "green-button"

= link_to t('action.edit-account'), edit_user_registration_path